[versions]
assertj = "3.27.6"
commonsLang = "3.20.0"
commonsText = "1.15.0"
gradleOci-junitJupiter = "0.8.0"
hivemq-extensionSdk = "4.2.0"
hivemq-mqttClient = "1.3.11"
jaxb-api = "2.3.3"
jaxb-impl = "2.3.9"
jetbrains-annotations = "26.0.2-1"
jetty = "11.0.26"
junit-jupiter = "5.10.0"
logback = "1.5.22"
mockito = "5.21.0"
testcontainers = "2.0.2"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
commonsText = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
gradleOci-junitJupiter = { module = "io.github.sgtsilvio:gradle-oci-junit-jupiter", version.ref = "gradleOci-junitJupiter" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxb-api" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb-impl" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet", version.ref = "jetty" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:testcontainers-hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "4.0.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.24.0" }
